coverage:
  notify:
    slack:
      default:
        url: "secret:H+wTfrYqVgWNIk6GIYpyB6pzv9kSqoqrFopnZCBtVgsOVXmtueQPC7Cy3pW6SZKpOqBNxdmIB5RA9ZdSTxjCzvBprwa2oIwRbtozjDgkzrVyvohPS44qgWcisz7CTNiCsxxkqKXoAyEutlYv4D+tYKUo/7w9EIZ3XyMU81OJ2G4="
        only_pulls: false
        branches: null
        flags: null
        paths: null
