language: java

jdk:
  - openjdk8

script:
  - jdk_switcher use openjdk8
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: unmani:4pBJoLwj5YBUNfFoSOjbVNcI