language: java

jdk:
  - openjdk11

# travis doesn't s
# - https://github.com/codecov/example-java-maven/blob/master/.travis.yml
# - https://github.com/cobertura/cobertura/issues/381
#script:
#  - "mvn cobertura:cobertura"
#
#after_success:
#  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: anmani:3ubVnvB71zrG3WQIFnLzoyCX

after_success:
  - mvn clean test jacoco:report coveralls:report
