codecov:
  token: 7bbeba9f-6005-444e-b654-a5458237dbb8
coverage:
  notify:
    slack:
      default:
        url: "secret:H+wTfrYqVgWNIk6GIYpyB6pzv9kSqoqrFopnZCBtVgsOVXmtueQPC7Cy3pW6SZKpOqBNxdmIB5RA9ZdSTxjCzvBprwa2oIwRbtozjDgkzrVyvohPS44qgWcisz7CTNiCsxxkqKXoAyEutlYv4D+tYKUo/7w9EIZ3XyMU81OJ2G4="
        message: "Coverage {{changed}} for {{owner}}/{{repo}}"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
